[package]
name = "digital-garden"
version = "0.1.0"
authors = ["Sam Marxz <sammarxz@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
